# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Builds and Uploads App to HockeyApp"
  lane :beta do
    increment_build_number
  	[["lifeline", "Release"]].each do |scheme_name, configuration|
  		gym(
			scheme: scheme_name,
  			configuration: configuration,
			export_method: "ad-hoc"
    	)
	
		hockey(
      		api_token: "39260d7d0f854f0880c7ef5532a0daa0"
    	)
  	end
  end
end
